#!/usr/local/bin/bash

NAME="proj"                              # Django Project Name
DJANGODIR=/usr/home/leea51/CS491-Research-Survey-Tool/proj #/home/$USER/myenv/myproject                        # Django Project Directory
SOCKFILE=/usr/home/leea51/CS491-Research-Survey-Tool/proj/run/gunicorn.sock     # Gunicorn Sock File
USER=leea51                                                # Django Project Running under user vagrant
GROUP=leea51                                                # Django Project Running under group vagrant
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=proj.settings                     # change 'myproject' with your project name
DJANGO_WSGI_MODULE=proj.wsgi                             # change 'myproject' with your project name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /usr/home/leea51/.virtualenvs/venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /usr/home/leea51/.virtualenvs/venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
