-- MySQL Script generated by MySQL Workbench
-- Sun 21 Jan 2018 02:02:24 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema surveydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema surveydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `surveydb` DEFAULT CHARACTER SET utf8 ;
USE `surveydb` ;

-- -----------------------------------------------------
-- Table `surveydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `researcher/participant` CHAR(1) NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surveydb`.`Survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`Survey` (
  `surveyID` INT NOT NULL,
  `survey_userID` INT NULL,
  PRIMARY KEY (`surveyID`),
  INDEX `usename_idx` (`survey_userID` ASC),
  CONSTRAINT `usename`
    FOREIGN KEY (`survey_userID`)
    REFERENCES `surveydb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surveydb`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`Question` (
  `questionID` INT NOT NULL,
  `question_surveyID` INT NULL,
  `questionType` VARCHAR(45) NOT NULL,
  `question_text` VARCHAR(65000) NULL,
  PRIMARY KEY (`questionID`, `questionType`),
  INDEX `surveyNum_idx` (`question_surveyID` ASC),
  CONSTRAINT `surveyID`
    FOREIGN KEY (`question_surveyID`)
    REFERENCES `surveydb`.`Survey` (`surveyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surveydb`.`Responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`Responses` (
  `responseID` INT NOT NULL,
  `response_questionID` INT NULL,
  `response_surveyID` INT NULL,
  `response_text` VARCHAR(65000) NULL,
  `responseType` VARCHAR(45) NULL,
  `response_userID` INT NULL,
  PRIMARY KEY (`responseID`),
  INDEX `fk_questionID_idx` (`response_questionID` ASC),
  INDEX `fk_surveyNum_idx` (`response_surveyID` ASC),
  INDEX `fk_responseType_idx` (`responseType` ASC),
  INDEX `fk_userID_idx` (`response_userID` ASC),
  CONSTRAINT `fk_questionID`
    FOREIGN KEY (`response_questionID`)
    REFERENCES `surveydb`.`Question` (`questionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surveyNum`
    FOREIGN KEY (`response_surveyID`)
    REFERENCES `surveydb`.`Survey` (`surveyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responseType`
    FOREIGN KEY (`responseType`)
    REFERENCES `surveydb`.`Question` (`questionType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userID`
    FOREIGN KEY (`response_userID`)
    REFERENCES `surveydb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
