# Generated by Django 2.0.1 on 2018-02-27 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('4006cd27-138b-441a-a385-46c6d7b4ea85'), primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('option_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('12a13385-7891-41e5-8b41-a6e2584e7821'), primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('option_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('e31ba468-ba48-4174-8a2d-39a811f7cb35'), primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_Id', models.UUIDField(default=uuid.UUID('71ce396d-08f1-4d38-8ec3-752b6c8a2f93'), primary_key=True, serialize=False)),
                ('response_text', models.CharField(max_length=400)),
                ('response_question_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_Id', models.UUIDField(default=uuid.UUID('019abcee-873b-4907-bd0a-eb35f919a2cc'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('creator_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TEQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('ce3a1aac-7964-4d3b-a597-4ba384e24823'), primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='response_survey_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='response',
            name='response_user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='question_survey_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='question_survey_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey'),
        ),
    ]
