# Generated by Django 2.0.1 on 2018-01-25 01:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_Id', models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=50)),
                ('question_text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('response_Id', models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('response_text', models.CharField(max_length=400)),
                ('response_question_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('survey_Id', models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_Id', models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='surveys',
            name='creator_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Users'),
        ),
        migrations.AddField(
            model_name='responses',
            name='response_survey_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Surveys'),
        ),
        migrations.AddField(
            model_name='responses',
            name='response_user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Users'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_survey_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Surveys'),
        ),
    ]
