# Generated by Django 2.0.2 on 2018-02-27 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('ac2dc3b9-3333-46cd-96bd-1fb03c56a076'), primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('option_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('1f093b00-8ce8-4be0-b3db-150d94873d7f'), primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('option_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('a5f25d77-b532-4d51-b14c-3ec9d07d7c00'), primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_Id', models.UUIDField(default=uuid.UUID('0a874b42-6f0c-4aba-ace2-7cbce89ae178'), primary_key=True, serialize=False)),
                ('response_text', models.CharField(max_length=400)),
                ('response_question_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_Id', models.UUIDField(default=uuid.UUID('2f8b66f8-c937-4ab2-a124-8de4c1bb36c1'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('creator_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TEQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('16d6c64c-7aaa-4b2f-b325-7f0a91f59ebb'), primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='response_survey_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='response',
            name='response_user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='question_survey_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='question_survey_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey'),
        ),
    ]
