# Generated by Django 2.0.1 on 2018-02-08 00:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('option_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('option_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TEQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(max_length=20),
        ),
    ]
