# Generated by Django 2.0.1 on 2018-02-13 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbquestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('3691d66f-94b1-4d5d-8f02-3de0e5073470'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('5d66ee79-52f3-45cd-ba84-5a57cf88f0ed'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('36701576-0c69-4eb4-8edc-87f87fadf3b3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_Id',
            field=models.UUIDField(default=uuid.UUID('b47ece98-0eae-4cb7-afa9-c92893a2f1ff'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_Id',
            field=models.UUIDField(default=uuid.UUID('aedb8601-ecc9-4cb4-933f-b0f6f287d88f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tequestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('14206eee-f622-4a2b-a7c1-9c8d28be6def'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Id',
            field=models.UUIDField(default=uuid.UUID('a075c80d-b91f-4c90-8b9e-6190dd3d286d'), primary_key=True, serialize=False),
        ),
    ]
