# Generated by Django 2.0.1 on 2018-02-13 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20180213_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CBQuestion',
        ),
        migrations.DeleteModel(
            name='MCQuestion',
        ),
        migrations.DeleteModel(
            name='TEQuestion',
        ),
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_5',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='Add question text', max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('facce7ba-935f-4adc-ba4d-8f476548290e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_Id',
            field=models.UUIDField(default=uuid.UUID('d98e4ae2-75f4-4aed-968e-e618794608dd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_Id',
            field=models.UUIDField(default=uuid.UUID('e042bddd-cfda-4f05-8a9c-9cbccaba5dac'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Id',
            field=models.UUIDField(default=uuid.UUID('0de83946-ed29-4743-9cbf-20f4f296a178'), primary_key=True, serialize=False),
        ),
    ]
