# Generated by Django 2.0.1 on 2018-02-11 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20180211_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_Id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='response',
            name='response_user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.User'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='creator_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.User'),
        ),
    ]
