# Generated by Django 2.0.1 on 2018-02-13 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20180213_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('eb931ea8-78c1-4591-8c1f-3549758f869e'), primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('option_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('7de8aeba-444d-4957-91da-2bd09b737372'), primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('option_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TEQuestion',
            fields=[
                ('question_Id', models.UUIDField(default=uuid.UUID('dac0ca01-a01c-4e45-b54e-ad2cd8d94485'), primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('7a6ad70a-ae45-4d07-ab3b-5f18f2e3c683'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_Id',
            field=models.UUIDField(default=uuid.UUID('70fe9efc-3051-49e4-953d-91938c6adc91'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_Id',
            field=models.UUIDField(default=uuid.UUID('0add1e2a-a7d2-4135-bab6-782f738a9064'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Id',
            field=models.UUIDField(default=uuid.UUID('abd21072-a626-4a1a-b128-4c64dcfef32f'), primary_key=True, serialize=False),
        ),
    ]
