# Generated by Django 2.0.1 on 2018-02-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20180211_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestion',
            name='question_survey_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
