# Generated by Django 2.0.2 on 2018-02-11 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20180211_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbquestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('d68d9c3d-1126-4f55-b121-7f7932e2bd18'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('b631b6bb-cf24-48e0-afbb-b68ebf372493'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('cce4b803-a130-4880-b846-5e81d011c134'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_survey_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_Id',
            field=models.UUIDField(default=uuid.UUID('27e27712-bd3d-482b-a385-151d105c0617'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='creator_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_Id',
            field=models.UUIDField(default=uuid.UUID('3324d06c-324f-459f-acd6-9435a096af14'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tequestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('1f92921d-d439-4825-aa3b-de73e7abffe8'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
