# Generated by Django 2.0.1 on 2018-02-13 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20180213_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_5',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AlterField(
            model_name='cbquestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('2b0d2011-27a0-42e4-af7f-62227510048b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('56cbb39d-4c13-4978-ba1b-880f5f84b4c7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('ec51f99c-937c-4ceb-8754-917cb01ee5ff'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_Id',
            field=models.UUIDField(default=uuid.UUID('2d876c2a-1aac-4e4d-860b-49d8d5de11fe'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_Id',
            field=models.UUIDField(default=uuid.UUID('c92b649f-fc1b-4694-b262-35b91794244d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tequestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('c2c6c943-db29-4cc5-ae33-ecdb29367518'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Id',
            field=models.UUIDField(default=uuid.UUID('2f63fed9-349e-4127-b392-8958261aad7d'), primary_key=True, serialize=False),
        ),
    ]
