# Generated by Django 2.0.2 on 2018-02-11 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20180211_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbquestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('922ac4ed-eeb3-4558-828d-f7a6273b7e18'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('2ae3b918-c98f-4144-811f-1bc00014e218'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('548dd6bb-99e5-42f2-8c9a-b9b4df8ef119'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_Id',
            field=models.UUIDField(default=uuid.UUID('de9834f6-ef4f-4095-9c5d-856e98130a97'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_Id',
            field=models.UUIDField(default=uuid.UUID('1acd222b-3231-4d79-92bd-045e23018ed8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tequestion',
            name='question_Id',
            field=models.UUIDField(default=uuid.UUID('b0326634-10c2-4c9e-a8dc-cae441808496'), primary_key=True, serialize=False),
        ),
    ]
